name: Docker Bake Check

on:
  push:
    branches:
      - main

jobs:
  bake-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/bake-action@v7
        with:
          files: docker-bake.hcl
          targets: validate-build
